name: simple_todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  flutter_staggered_animations: ^1.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
